export const AUTH_LOGGED_IN_SUCCESS = 'AUTH_LOGGED_IN_SUCCESS';
export const AUTH_INITIALIZATION_DONE = 'AUTH_INITIALIZATION_DONE';
export const AUTH_LOGGED_OUT_SUCCESS = 'AUTH_LOGGED_OUT_SUCCESS';
export const ADD_COMIC_SUCCESS = 'ADD_COMIC_SUCCESS';
export const GET_LATEST_COMICS_SUCCESS = 'GET_LATEST_COMICS_SUCCESS';
