// Auth types
export const AUTH_LOGGED_IN_SUCCESS = 'AUTH_LOGGED_IN_SUCCESS';
export const AUTH_INITIALIZATION_DONE = 'AUTH_INITIALIZATION_DONE';
export const AUTH_LOGGED_OUT_SUCCESS = 'AUTH_LOGGED_OUT_SUCCESS';

// Comic Types
export const ADD_COMIC_SUCCESS = 'ADD_COMIC_SUCCESS';
export const GET_LATEST_COMICS_SUCCESS = 'GET_LATEST_COMICS_SUCCESS';
export const GET_ALL_COMICS = 'GET_ALL_COMICS';
export const GET_CURRENT_COMIC = 'GET_CURRENT_COMIC';
export const GET_PREV_COMIC = 'GET_PREV_COMIC';
export const GET_NEXT_COMIC = 'GET_NEXT_COMIC';

export const LOAD_STATS_SUCCESS = 'LOAD_STATS_SUCCESS';
