// Auth types
export const AUTH_LOGGED_IN_SUCCESS = 'AUTH_LOGGED_IN_SUCCESS';
export const AUTH_INITIALIZATION_DONE = 'AUTH_INITIALIZATION_DONE';
export const AUTH_LOGGED_OUT_SUCCESS = 'AUTH_LOGGED_OUT_SUCCESS';

// Comic Types
export const ADD_COMIC = 'ADD_COMIC';
export const GET_LATEST_COMIC = 'GET_LATEST_COMICS_SUCCESS';
export const GET_ALL_COMICS = 'GET_ALL_COMICS';
export const GET_CURRENT_COMIC = 'GET_CURRENT_COMIC';
export const GET_PREV_COMIC = 'GET_PREV_COMIC';
export const GET_NEXT_COMIC = 'GET_NEXT_COMIC';
export const UPLOADING_COMIC = 'UPLOADING_COMIC';
export const GET_FAVORITE_COMICS = 'GET_FAVORITE_COMICS'

export const LOAD_STATS_SUCCESS = 'LOAD_STATS_SUCCESS';
export const GET_ADMIN_LIST = 'GET_ADMIN_LIST';
export const USER_IS_ADMIN_SUCCESS = 'USER_IS_ADMIN_SUCCESS';
